config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post :add_product
      post :set_product_alias
      post :remove_product
      post :fetch_address_from_economic
      get :edit_products
      get :edit_contact_address
      get :affiliate_dashboard
      
      patch :update_contact_address
      resources :products, only: [] do
        get :edit_price_scheme
        patch :update_price_scheme
        patch :default_price_scheme
        patch :cargoflux_price_scheme
      end
      
      get :epay_subscribe
      get :shipments
    end
  end

  resources :products do
    member do
      get :edit_cost
      patch :update_cost_scheme
      get :edit_default_price
      patch :update_default_price_scheme
    end
  end

  resources :transporters

  resources :shipments do
    member do
      post :submit
      post :callback
      post :reprint
      post :email
      get :copy
    end
  end
  post 'shipments/calculate_price', to: 'shipments#calculate_price'
  post 'shipments/upload_csv', to: 'shipments#upload_csv'
  get 'bulk_import', to: 'shipments#bulk_import'

  resources :invoices, only: [:show] do
    get :shipments
    get :export_rows
  end
  resources :invoices, defaults: { format: 'xlsx' }
  
  resources :addresses do
    member do
      get :send_to
      get :json
    end
  end
  
  
  

  resources :import_formats do
    member do
      get :edit_for_user
    end
  end

  resources :invoices do
  end
  

  root 'sessions#index'
  post 'login', to: 'sessions#login_attempt'
  get 'home', to: 'sessions#home'
  get 'logout', to: 'sessions#logout'  
  get 'forgot_password', to: 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password'
  get 'urp/:email/:key', as: 'new_password', to: 'sessions#new_password', :constraints => { :email => /[^\/]+/ }
  post 'update_password', to: 'sessions#update_password'

  post 'api/products', to: 'api#product_codes'
  post 'api/create_shipment', to: 'api#create_shipment'
  post 'api/fresh_labels', to: 'api#fresh_labels'
  post 'api/recent_failures', to: 'api#recent_failures'
  post 'api/import', to: 'api#upload_csv'
  post 'api/validate_key', to: 'api#validate_key'
  post 'api/shipment_info', to: 'api#shipment_info'
  post 'api/client_version', to: 'api#client_version'
  post 'api/is_code_pickup_point', to: 'api#is_code_pickup_point'
  post 'api/pn/servicepoints', to: 'api#pn_servicepoints_by_address'
  post 'api/gls/servicepoints', to: 'api#gls_servicepoints_by_address'
  post 'api/dao/servicepoints', to: 'api#dao_servicepoints_by_address'
  post 'api/get_price', to: 'api#get_price'
  post 'api/economic_invoice_captured', to: 'api#economic_invoice_captured'
  post 'api/economic_invoice_updated', to: 'api#economic_invoice_updated'
  post 'api/update_pending_booking_states', to: 'api#update_pending_booking_states'
  post 'api/mark_shipment_printed', to: 'api#mark_shipment_printed'

  get 'account', to: 'account#index', as: 'account'
  get 'account/change_password', to: 'account#change_password', as: 'change_password'
  post 'account/do_change_password', to: 'account#do_change_password', as: 'do_change_password'
  get 'account/products', to: 'account#products', as: 'my_products'
  patch 'account/product/:id/', to: 'account#update_product', as: 'user_product'
  get 'account/invoices', to: 'account#invoices', as: 'my_invoices'
  get 'account/invoices/:id', to: 'account#invoices_show', as: 'my_invoices_show'
  get 'account/invoices/:id/download', to: 'account#invoice_download', as: 'download_invoice'
  get 'account/invoices/:id/shipments', to: 'account#invoices_shipments', as: 'my_invoices_shipments'
  get 'account/epay_subscribe', to: 'account#epay_subscribe', as: 'epay_subscribe'
  post 'account/epay_delete_subscription', to: 'account#epay_delete_subscription', as: 'epay_delete_subscription'

  get 'settings', to: 'settings#index', as: 'settings'
  patch 'settings/:id/update', to: 'settings#update', as: 'user_setting'

  get 'billing/user/:id', to: 'billing#user', as: 'user_billing'
  get 'billing/user/:id/edit_prices', to: 'billing#edit_prices', as: 'user_edit_prices'
  get 'billing/user/:id/edit_additional_charges', to: 'billing#edit_additional_charges', as: 'user_edit_additional_charges'
  post 'billing/invoice', to: 'billing#invoice', as: 'invoice_all'
  post 'billing/user/:id/update_prices', to: 'billing#update_prices', as: 'user_update_prices'
  post 'billing/user/:id/update_additional_charges', to: 'billing#update_additional_charges', as: 'user_update_additional_charges'
  post 'billing/user/:id/add_additional_charge', to: 'billing#add_additional_charge', as: 'user_add_additional_charge'
  post 'billing/invoice/:id/submit', to:'billing#submit_invoice', as: 'submit_invoice'
  post 'billing/invoice/:id/capture', to: 'billing#capture_invoice', as: 'capture_invoice' 
  post 'billing/invoice/:id/identify', to: 'billing#identify_economic_id', as: 'identify_economic_id'
  post 'billing/invoice/:id/send_email', to: 'billing#send_invoice_email', as: 'send_invoice_email'
  get 'billing', to: 'billing#overview', as: 'billing_overview'

  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  get 'admin/shipment/:id', to: 'admin#show_shipment', as: 'admin_shipment'
  get 'admin/tools', to: 'admin#tools', as: 'admin_tools'
  post 'admin/tools/verify_billable_shipments', to: 'admin#verify_billable_shipments', as: 'admin_verify_billable'
  post 'admin/tools/update_shipping_states', to: 'admin#update_shipping_states', as: 'admin_update_shipping_states'
  post 'admin/tools/update_booking_states', to: 'admin#update_booking_states', as: 'admin_update_booking_states'
  post 'admin/tools/automatic_invoicing', to: 'admin#automatic_invoicing', as: 'admin_automatic_invoicing'
  post 'admin/tools/fetch_economic_data', to: 'admin#fetch_economic_data', as: 'admin_economic_fetch'
  post 'admin/tools/process_additional_charges', to: 'admin#process_additional_charges', as: 'admin_process_additional_charges'
  post 'admin/tools/approve_additional_charges', to: 'admin#approve_additional_charges', as: 'admin_approve_additional_charges'
  post 'admin/tools/import_ftp_uploads', to: 'admin#import_ftp_uploads', as: 'admin_import_ftp_uploads'
  post 'admin/tools/apply_subscription_fees', to: 'admin#apply_subscription_fees', as: 'admin_apply_subscription_fees'
  post 'admin/tools/update_cargoflux_prices', to: 'admin#update_cargoflux_prices', as: 'admin_update_cargoflux_prices'
  
  get 'affiliate/dashboard', to: 'affiliate#dashboard', as: 'affiliate_dashboard'

end

app/views/admin/dashboard.html.erb
<h1 class='page-header'>Dashboard</h1>


<%= render :partial => 'util/date_range_filter', :locals => {:nopanel => true } %>
<div class='panel panel-default'>
	<div class='panel-heading'>
	  Total Bookings:
      <span class='pull-right'>
      <% total = 0
         for date in @booking_report.keys
            total += @booking_report[date]['total']
         end
         %>
      <%= total %>
      </span>
	</div>
	<div class='panel-body'>  
	  <%= render :partial => 'util/booking_report', :locals => {:report => @booking_report } %>
	</div> 
</div>

<div class='panel panel-default'>
	<div class='panel-heading'>
		Invoice Data
	</div>
	<div class='panel-body'>  
	  <%= render :partial => 'util/invoice_report', :locals => {:report => @invoice_report } %>
	</div>
</div>




<% if false %>
<%= render :partial => 'util/date_range_filter' %>

<div class='panel panel-default'>
	<div class='panel-heading'>Turnover in Period</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>User</th>
					<th>Completed shipment bookings</th>
					<th>Value of bookings</th>
					<th>Number of invoices</th>
					<th>Total amount invoiced</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>
						TOTAL
					</th>
					<th>
						<%= @nShipments %>
					</th>
					<th>
						<%= currency @value %>
					</th>
					<th>
						<%= @nInvoices %>
					</th>
					<th>
						<%= currency @totalInvoiced %>
					</th>
				</tr>
				<% @customerData.each do |row| %>
				<tr>
					<td>
						<%= row['email'] %>
					</td>
					<td>
						<%= row['booked'] %>
					</td>
					<td>
						<%= currency row['value'] %>
					</td>
					<td>
						<%= row['invoices'] %>
					</td>
					<td>
						<%= currency row['invoiced'] %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<% end %>

app/views/admin/process_additional_charges.html.erb
<%= form_tag '/admin/tools/approve_additional_charges' do %>
<h1 class='page-header'>
	Additional Charges
	<span class='pull-right'><button type='submit' class='btn btn-primary'>Approve</button></span>
</h1>

<div class='panel panel-default'>
	<div class='panel-heading'>
		Approve charges (<%= @charges.length %>)
		
	</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Shipment</th>
					<th>User</th>
					<th>Service</th>
					<th>Cost</th>
					<th>Price</th>
				</tr>
			</thead>
			<tbody>
			<% @charges.each do |c| %>
			<input type='hidden' name='user[]' value='<%= c.user.id %>'/>
			<input type='hidden' name='cost[]' value='<%= c.cost %>'/>
			<input type='hidden' name='service[]' value='<%= c.service %>'/>
			<input type='hidden' name='shipment[]' value='<%= c.shipment.id %>'/>
			<tr>
				<td>
					<%= c.shipment.awb %>
				</td>
				<td>
					<%= c.user.name %>
				</td>
				<td>
					<%= c.service %>
				</td>
				<td>
					<%= currency c.cost %>
				</td>
				<td>
					<input type='text' class='form-control' name='price[]' value='<%= c.price %>'/>
				</td>
			</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>
<% end %>

app/views/admin/tools.html.erb
<h1 class='page-header'>Tools</h1>

<div class='panel panel-default'>
	<div class='panel-heading'>Verify Billable Shipments</div>
	<div class='panel-body'>
		<div class='import-csv'>
		  <%= form_tag '/admin/tools/verify_billable_shipments', :multipart=>true do %>
		  <%= label_tag(:file, "") %>
		  <%= file_field_tag :file %>
		  <%= submit_tag "Upload" %>
		  <% end %>
		</div>
	</div>
</div>

<div class='panel panel-default'>
	<div class='panel-heading'>Process Additional Charges</div>
	<div class='panel-body'>
		<div class='import-csv'>
		  <%= form_tag '/admin/tools/process_additional_charges', :multipart=>true do %>
		  <%= label_tag(:file, "") %>
		  <%= file_field_tag :file %>
		  <%= submit_tag "Upload" %>
		  <% end %>
		</div>
	</div>
</div>



<div class='panel panel-default'>
	<div class='panel-heading'>Cron Jobs</div>
	<div class='panel-body'>
		<div class='panel panel-default'>
			<div class='panel-heading'>Update booking states</div>
			<div class='panel-body'>
				<p>Fetch booking states for bookings stuck in "Response_pending".
					(<%= @n_response_pending %> bookings pending)
					</p>
				
				<%= link_to 'Run update', admin_update_booking_states_path, method: :post%>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Update Shipping States</div>
			<div class='panel-body'>
				<%= link_to 'Run update', admin_update_shipping_states_path,
          			method: :post%>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Perform Automatic Invoicing</div>
			<div class='panel-body'>
				<%= link_to 'Run invoicing', admin_automatic_invoicing_path,
          			method: :post%>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Fetch e-conomic data</div>
			<div class='panel-body'>
				<%= link_to 'Fetch now', admin_economic_fetch_path,
          			method: :post%>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Import FTP uploads</div>
			<div class='panel-body'>
				<%= link_to 'Import', admin_import_ftp_uploads_path, method: :post %>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Apply subscription fees</div>
			<div class='panel-body'>
				<%= link_to 'Apply', admin_apply_subscription_fees_path, method: :post %>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Update product prices from cargoflux</div>
			<div class='panel-body'>
				<%= link_to 'Update', admin_update_cargoflux_prices_path, method: :post %>
			</div>
		</div>
	</div>
</div>

app/views/admin/verify_billable_shipments.html.erb
<%= cbox do-%>
<%= cbox_header('Results') do-%>

<% end %>

<div class='row'>
  <div class='col-xs-4'>
    <%= kv_box({
	'Unknown shipments' => @n_unknown_shipments,
    'Known shipments' => @n_known_shipments,
    'Warnings' => @warnings,
    'Expected cost' => currency(@total_expected_cost),
    'Actual cost' => currency(@total_actual_cost),
    'Price' => currency(@total_price),
    'Expected balance' => currency(@total_price - @total_expected_cost),
    'Actual balance' => currency(@total_price - @total_actual_cost),
    'Divergence' => currency(@total_expected_cost - @total_actual_cost)
	}, false)
	%>
  </div>
</div>

<% end %>

<%= cbox do-%>
<%= cbox_subheader('Shipments') do-%>

<% end %>

<%= tbl true do-%>
<thead>
  <tr>
    <th>ID</th>
    <th>Warning</th>
    <th>Expected cost</th>
    <th>Actual cost</th>
    <th>Price</th>
    <th>Expected balance</th>
    <th>Actual balance</th>
    <th>Divergence</th>
  </tr>
</thead>
<tbody>
  <% @rows.each do |row| %>
  <tr <% if row[:warning] %>class='alert-danger'<% end %>>
    <td><%= row[:id] %></td>
    <td><%= row[:warning] ? row[:warning] : '' %></td>
    <td><%= currency row[:expected_cost] %></td>
    <td><%= currency row[:actual_cost] %></td>
    <td><%= currency row[:price] %></td>
    <td><%= currency row[:expected_balance] %></td>
    <td><%= currency row[:actual_balance] %></td>
    <td><%= currency row[:expected_cost] - row[:actual_cost]%></td>
  </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
    <td/>
    <td/>
    <td><%= currency @total_expected_cost %></td>
    <td><%= currency @total_actual_cost %></td>
    <td><%= currency @total_price %></td>
    <td><%= currency @total_price - @total_expected_cost %></td>
    <td><%= currency @total_price - @total_actual_cost %></td>
    <td><%= currency @total_expected_cost - @total_actual_cost%></td>
  </tr>
</tfoot>
<% end %>

<% end %>



<% if false %>
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<td>Unknown shipments</td><td>Incomplete shipments</td><td>Total</td>
		</tr>
		<tr>
			<td>
				<%= @unknown.length %>
			</td>
			<td>
				<%= @incomplete.length %>
			</td>
			<td>
				<%= @unknown.length + @incomplete.length%>
			</td>
		</tr>
	</table>
</div>	

<h2 class="sub-header">Unknown shipments</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead><tr><th>ID</th></tr></thead>
		<% @unknown.each do |id| %>
		<tr>
			<td><%= id %></td>
		</tr>
		<% end %>
	</table>
</div>

<h2 class="sub-header">Incomplete shipments</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead><tr><th>ID</th><th>Shipping state</th></tr></thead>
		<% @incomplete.each do |s| %>
		<tr>
		 	<td><%= link_to "#{s.pretty_id}", admin_shipment_path(s) %></td>
			<td><%= s.shipping_state %></td>
		</tr>
		<% end %>
	</table>
</div>
<% end %>