config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post :add_product
      post :set_product_alias
      post :remove_product
      post :fetch_address_from_economic
      get :edit_products
      get :edit_contact_address
      get :affiliate_dashboard
      
      patch :update_contact_address
      resources :products, only: [] do
        get :edit_price_scheme
        patch :update_price_scheme
        patch :default_price_scheme
        patch :cargoflux_price_scheme
      end
      
      get :epay_subscribe
      get :shipments
    end
  end

  resources :products do
    member do
      get :edit_cost
      patch :update_cost_scheme
      get :edit_default_price
      patch :update_default_price_scheme
    end
  end

  resources :transporters

  resources :shipments do
    member do
      post :submit
      post :callback
      post :reprint
      post :email
      get :copy
    end
  end
  post 'shipments/calculate_price', to: 'shipments#calculate_price'
  post 'shipments/upload_csv', to: 'shipments#upload_csv'
  get 'bulk_import', to: 'shipments#bulk_import'

  resources :invoices, only: [:show] do
    get :shipments
    get :export_rows
  end
  resources :invoices, defaults: { format: 'xlsx' }
  
  resources :addresses do
    member do
      get :send_to
      get :json
    end
  end
  
  
  

  resources :import_formats do
    member do
      get :edit_for_user
    end
  end

  resources :invoices do
  end
  

  root 'sessions#index'
  post 'login', to: 'sessions#login_attempt'
  get 'home', to: 'sessions#home'
  get 'logout', to: 'sessions#logout'  
  get 'forgot_password', to: 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password'
  get 'urp/:email/:key', as: 'new_password', to: 'sessions#new_password', :constraints => { :email => /[^\/]+/ }
  post 'update_password', to: 'sessions#update_password'

  post 'api/products', to: 'api#product_codes'
  post 'api/create_shipment', to: 'api#create_shipment'
  post 'api/fresh_labels', to: 'api#fresh_labels'
  post 'api/recent_failures', to: 'api#recent_failures'
  post 'api/import', to: 'api#upload_csv'
  post 'api/validate_key', to: 'api#validate_key'
  post 'api/shipment_info', to: 'api#shipment_info'
  post 'api/client_version', to: 'api#client_version'
  post 'api/is_code_pickup_point', to: 'api#is_code_pickup_point'
  post 'api/pn/servicepoints', to: 'api#pn_servicepoints_by_address'
  post 'api/gls/servicepoints', to: 'api#gls_servicepoints_by_address'
  post 'api/dao/servicepoints', to: 'api#dao_servicepoints_by_address'
  post 'api/get_price', to: 'api#get_price'
  post 'api/economic_invoice_captured', to: 'api#economic_invoice_captured'
  post 'api/economic_invoice_updated', to: 'api#economic_invoice_updated'
  post 'api/update_pending_booking_states', to: 'api#update_pending_booking_states'
  post 'api/mark_shipment_printed', to: 'api#mark_shipment_printed'

  get 'account', to: 'account#index', as: 'account'
  get 'account/change_password', to: 'account#change_password', as: 'change_password'
  post 'account/do_change_password', to: 'account#do_change_password', as: 'do_change_password'
  get 'account/products', to: 'account#products', as: 'my_products'
  patch 'account/product/:id/', to: 'account#update_product', as: 'user_product'
  get 'account/invoices', to: 'account#invoices', as: 'my_invoices'
  get 'account/invoices/:id', to: 'account#invoices_show', as: 'my_invoices_show'
  get 'account/invoices/:id/download', to: 'account#invoice_download', as: 'download_invoice'
  get 'account/invoices/:id/shipments', to: 'account#invoices_shipments', as: 'my_invoices_shipments'
  get 'account/epay_subscribe', to: 'account#epay_subscribe', as: 'epay_subscribe'
  post 'account/epay_delete_subscription', to: 'account#epay_delete_subscription', as: 'epay_delete_subscription'

  get 'settings', to: 'settings#index', as: 'settings'
  patch 'settings/:id/update', to: 'settings#update', as: 'user_setting'

  get 'billing/user/:id', to: 'billing#user', as: 'user_billing'
  get 'billing/user/:id/edit_prices', to: 'billing#edit_prices', as: 'user_edit_prices'
  get 'billing/user/:id/edit_additional_charges', to: 'billing#edit_additional_charges', as: 'user_edit_additional_charges'
  post 'billing/invoice', to: 'billing#invoice', as: 'invoice_all'
  post 'billing/user/:id/update_prices', to: 'billing#update_prices', as: 'user_update_prices'
  post 'billing/user/:id/update_additional_charges', to: 'billing#update_additional_charges', as: 'user_update_additional_charges'
  post 'billing/user/:id/add_additional_charge', to: 'billing#add_additional_charge', as: 'user_add_additional_charge'
  post 'billing/invoice/:id/submit', to:'billing#submit_invoice', as: 'submit_invoice'
  post 'billing/invoice/:id/capture', to: 'billing#capture_invoice', as: 'capture_invoice' 
  post 'billing/invoice/:id/identify', to: 'billing#identify_economic_id', as: 'identify_economic_id'
  post 'billing/invoice/:id/send_email', to: 'billing#send_invoice_email', as: 'send_invoice_email'
  get 'billing', to: 'billing#overview', as: 'billing_overview'

  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  get 'admin/shipment/:id', to: 'admin#show_shipment', as: 'admin_shipment'
  get 'admin/tools', to: 'admin#tools', as: 'admin_tools'
  post 'admin/tools/verify_billable_shipments', to: 'admin#verify_billable_shipments', as: 'admin_verify_billable'
  post 'admin/tools/update_shipping_states', to: 'admin#update_shipping_states', as: 'admin_update_shipping_states'
  post 'admin/tools/update_booking_states', to: 'admin#update_booking_states', as: 'admin_update_booking_states'
  post 'admin/tools/automatic_invoicing', to: 'admin#automatic_invoicing', as: 'admin_automatic_invoicing'
  post 'admin/tools/fetch_economic_data', to: 'admin#fetch_economic_data', as: 'admin_economic_fetch'
  post 'admin/tools/process_additional_charges', to: 'admin#process_additional_charges', as: 'admin_process_additional_charges'
  post 'admin/tools/approve_additional_charges', to: 'admin#approve_additional_charges', as: 'admin_approve_additional_charges'
  post 'admin/tools/import_ftp_uploads', to: 'admin#import_ftp_uploads', as: 'admin_import_ftp_uploads'
  post 'admin/tools/apply_subscription_fees', to: 'admin#apply_subscription_fees', as: 'admin_apply_subscription_fees'
  post 'admin/tools/update_cargoflux_prices', to: 'admin#update_cargoflux_prices', as: 'admin_update_cargoflux_prices'
  
  get 'affiliate/dashboard', to: 'affiliate#dashboard', as: 'affiliate_dashboard'

end

app/controllers/billing_controller.rb
include Economic
include Epay
using PatternMatch
class BillingController < ApplicationController
  before_filter :authenticate_admin
  
  
  def user
    @user = User.find(params[:id])
    @invoices = @user.invoices.order(id: :desc).paginate(:page => params[:page], :per_page => DEFAULT_PER_PAGE)
  end
  
  def edit_prices
    @user = User.find(params[:id])
  end
  
  def edit_additional_charges
    @user = User.find(params[:id])
  end
  
  def update_prices
    @user = User.find(params[:id])
    data = params.require(:shipments)
    data.each do |shipment_id, row|
      shipment = Shipment.find shipment_id
      if shipment.user != @user
        raise 'Unknown logical error..'
      end
      shipment.final_price = row['price'] == '' ? shipment.price : row['price'].to_f
      shipment.final_diesel_fee = row['diesel_fee'] == '' ? shipment.diesel_fee : row['diesel_fee'].to_f
      shipment.save
    end
    redirect_to :action => :user
  end
  
  def update_additional_charges
    @user = User.find(params[:id])
    trash = params[:delete]
    if trash == nil
      trash = []
    end
    ids = params[:cid] - trash
    prices = params[:price]
    
    trash.each do |id|
      AdditionalCharge.find(id).destroy
    end
    
    (0..ids.length - 1).each do |i|
      c = AdditionalCharge.find(ids[i])
      c.price = prices[i]
      c.save
    end
    
    redirect_to :action => :user
  end
  
  def add_additional_charge
    @user = User.find params[:id]
    
    charge = AdditionalCharge.new
    charge.user = @user
    charge.cost = params[:charge][:cost]
    charge.price = params[:charge][:price]
    charge.description = params[:charge][:description]
    charge.product_code = 'custom_charge'
    charge.save
    
    redirect_to :back
  end
  
  def invoice
    user = User.find(params[:user_id])
    begin
      user.do_invoice
    rescue PriceConfigException => e
      flash[:error] = e.issue
    end
    redirect_to user_billing_path(user)
  end
  
  # Submit invoice draft to e-conomic
  def submit_invoice
    invoice = Invoice.find(params[:id])
    if invoice.editable?
      match(Economic.submit_invoice(invoice)) do
        with(_[:error, issue]) do
          flash[:error] = issue
        end
        with(res) do
        end
      end
    else
      flash[:error] = 'This invoice is already booked.'
    end
    redirect_to user_billing_path(invoice.user)
  end
  
  def capture_invoice
    invoice = Invoice.find(params[:id])
    if invoice.capturable?
      match(Epay.capture_invoice(invoice)) do
        with(_[:error, issue]) do
          flash[:error] = issue
        end
        with(res) do
        end
      end
    else
      flash[:error] = 'This invoice can not be captured.'
    end
    redirect_to :back
  end

  def send_invoice_email
    invoice = Invoice.find params[:id]
    invoice.send_email
    redirect_to :back
  end
  
  def overview
     # Bad in-memory ordering. Todo: put uninvoiced shipment count in database
    @users = User.customer.sort_by  {|user| user.n_uninvoiced_shipments}.reverse.find_all {|user| user.n_uninvoiced_shipments > 0}

    @unpaid_invoices = Invoice.where(sent_to_economic: true, paid: false).order('created_at DESC')
  end
  
  def identify_economic_id
    invoice = Invoice.find params[:id]
    match(Economic.identify_booked_invoice invoice) do
      with(_[:error, issue]) do
        flash[:error] = issue
      end
      with(res) do
      end
    end
    redirect_to :back
  end
  
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/views/billing/edit_additional_charges.html.erb
<%= form_tag(user_update_additional_charges_path(@user), id: 'price-form') do %>
<h1 class='page-header'>Pending Additional Charges</h1>
<div class='panel panel-default'>
	<div class='panel-heading'>Additional Charges</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Shipment</th>
					<th>Description</th>
					<th>Cost</th>
					<th>Price</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @user.uninvoiced_additional_charges.each do |c| %>
				<tr>					
					<td><% if c.shipment %><%= link_to "#{c.shipment.pretty_id}", admin_shipment_path(c.shipment) %><%end%></td>
					<td><%= c.description %></td>
					<td><%= currency c.cost %></td>
					<input type='hidden' name='cid[]' value='<%= c.id %>'/>
					<td>
						<input type='text' name='price[]' value='<%= c.price %>' class='form-control'/>
					</td>
					<td>
						<input type='checkbox' value='<%= c.id %>' name='delete[]' class='form-control'/>
					</td>
				</tr>
				<% end %>
			</tbody>
			<tfoot>
				<tr>
					<td></td><td></td><td></td><td></td>
					<td><button type='submit' class='btn btn-primary form-control'>Submit</button></td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>



<% end %>

<%= form_tag(user_add_additional_charge_path(@user), id: 'additional-charge-form') do %>
<div class='panel panel-default'>
	<div class='panel-heading'>Add custom charge</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Description</th><th>Cost</th><th>Price</th><th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<%= bstxt_field :charge, :description %>
					</td>
					<td>
						<%= bstxt_field :charge, :cost %>
					</td>
					<td>
						<%= bstxt_field :charge, :price %>
					</td>
					<td>
						<button type='submit' class='btn btn-primary form-control'>Submit</button>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<% end %>

app/views/billing/edit_prices.html.erb
<%= form_tag(user_update_prices_path(@user), id: 'price-form') do %>
<h1 class='page-header'>Pending Shipments</h3>
<div class='panel panel-default'>
	<div class='panel-heading'>Shipments</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>ID</th><th>Product</th><th>Calculated Cost</th><th>Calculated Price</th><th>Adjusted Price</th>
					<th>Calculated Diesel Fee</th><th>Adjusted Diesel Fee</th>
				</tr>
			</thead>
			<tbody>
				<% @user.uninvoiced_shipments.each do |shipment| %>
					<tr>
						<td>
							<%= link_to "#{shipment.pretty_id}", admin_shipment_path(shipment) %>
						</td>
						<td><%= shipment.product.name %></td>
						<td>
							<%= currency shipment.cost %>
						</td>
						<td>
							<%= currency shipment.price %>
						</td>
						<td>
							<%= bstxt_field('shipments[' + shipment.id.to_s + ']', 'price', value: shipment.final_price) %>
						</td>
						<td>
							<%= currency shipment.diesel_fee %>
						</td>
						<td>
							<%= bstxt_field('shipments[' + shipment.id.to_s + ']', 'diesel_fee', value: shipment.final_diesel_fee) %>
						</td>
					</tr>
				<% end %>
			</tbody>			
			<tfoot>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td><button onclick='resetPrices()' type='button' class='btn btn-lg btn-default btn-block'>Reset prices</button></td>
					<td><button type='submit' class='btn btn-lg btn-primary btn-block'>Update</button></td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

<script type='text/javascript'>
	function resetPrices(){
		$('#price-form').find('[type=text]').each(
			function(index){
				var input = $(this);
				input.val('');
			}
		);
	}
</script>
<% end %>

app/views/billing/overview.html.erb
<h1 class='page-header'>Billing overview</h1>

<div class='panel panel-default'>
	<div class='panel-heading'>Billing Status</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<th>User</th>
				<th>Last invoice date</th>
				<th>Uninvoiced shipments</th>
				<th>Uninvoiced additional charges</th>
				<th>Cost</th>
				<th>Price</th>
				<th>Diesel fee</th>
				<th>Total balance</th>
				<th>User Billing Overview</th>
			</thead>
			<tbody>
				<% @users.each do |user| %>
				<% cost, price, diesel_fee = user.balance %>
				<tr>
					<td><%= link_to user.name, user_path(user) %></td>
					<td><%= print_date user.last_invoice_date %></td>
					<td><%= user.n_uninvoiced_shipments %></td>
					<td><%= user.n_uninvoiced_additional_charges %></td>
					<td><%= currency cost %></td>
					<td><%= currency price %></td>
					<td><%= currency diesel_fee %></td>
					<td><%= currency price + diesel_fee %></td>
					<td><%= link_to 'Billing', user_billing_path(user) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>	
	</div>
</div>


<div class='panel panel-default'>
  <div class='panel-heading'>Unpaid Invoices</div>
  <div class='panel-body'>
    <table class='table table-striped'>
      <thead>
        <th>User</th>
        <th>Invoice</th>
        <th>Date</th>
        <th>Netto</th>
      </thead>
      <tbody>
        <% @unpaid_invoices.each do |invoice| %>
        <tr <% if invoice.capturable? %>style="background-color:orange;"<% end %>>
          <td><%= link_to invoice.user.name, user_path(invoice.user) %></td>
          <td><%= link_to invoice.pretty_id, invoice_path(invoice) %></td>
          <td><%= print_date invoice.created_at %></td>
          <td><%= currency invoice.amount %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/billing/user.html.erb
<h1 class='page-header'>User Billing: <%= @user.name %></h1>

<div class='panel panel-default'>
	<div class='panel-heading'>Current Balance</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Shipments <%= link_to 'Edit', user_edit_prices_path(@user) %></th>
					<th>Additional Charges <%= link_to 'Edit', user_edit_additional_charges_path(@user)%></th>
					<th>Billing type</th>
					<th>Cost</th>
					<th>Price</th>
					<th>Diesel Fee</th>	
					<th>Invoice</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					
					<td><%= @user.n_uninvoiced_shipments %></td>
					<td><%= @user.n_uninvoiced_additional_charges %></td>
					<td><%= @user.billing_type_title %></td>
					<% cost, price, fee = @user.balance %>
					<td>
						<%= currency cost %>
					</td>
					<td>
						<%= currency price %>
					</td>
					<td>
						<%= currency fee %>	
					</td>
					
					<td>
						<% if price + fee == 0 %>
							<% disable_invoice = true%>
							Cannot create invoice: nothing pending
						<% elsif false and issues %>
							<% disable_invoice = true%>
							Cannot create invoice: some prices could not be determined (see shipments)
						<% end %>
						<%= form_tag invoice_all_path, method: :post do %>
							<%= hidden_field_tag :user_id, @user.id %>
							<button <%= disable_invoice ? 'disabled' : '' %> class="btn btn-lg btn-primary btn-block" type="submit">Create invoice</button>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class='panel panel-default'>
	<div class='panel-heading'>History</div>
	<div class='panel-body'>
		<div class='panel panel-default'>
			<div class='panel-heading'>Totals</div>
			<div class='panel-body'>
				<table class='table table-striped'>
					<thead>
						<tr>
							<th>Shipments Invoiced</th>
							<th>Netto</th>
                            <th>Gross</th>
                            <th>Profit</th>
                            <th>House Commission</th>
                            <th>Affiliate Commission</th>
						</tr>
					</thead>
                    <% totals = @user.get_totals %>
					<tbody>
						<tr>
						  <td><%= totals.n_shipments %></td>
                          <td><%= currency totals.netto %></td>
                          <td><%= currency totals.gross %></td>
                          <td><%= currency totals.profit %></td>
                          <td><%= currency totals.house_commission %></td>
                          <td><%= currency totals.affiliate_commission %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class='panel panel-default'>
			<div class='panel-heading'>Invoices</div>
			<div class='panel-body'>
				<%= grid_before @invoices %>
				<table class='table table-striped'>
					<thead>
						<tr>
						  <th>ID</th><th>Timestamp</th><th>Shipments</th><th>Netto</th><th>Undo invoice</th>
                          <th>Sent to e-conomic?</th><th>Captured online?</th>
                          <th>Paid?</th>
						</tr>	
					</thead>
					<tbody>
						<% @invoices.each do |invoice| %>
							<tr>
								<td><%= link_to invoice.pretty_id, invoice_path(invoice) %></td>
								<td><%= print_datetime invoice.created_at %></td>
								<td><%= invoice.n_shipments %></td>
								<td><%= currency invoice.amount %></td>
								<td>
                                  <% if invoice.editable? %>
									<%= link_to 'Undo', invoice_path(invoice),
							              method: :delete,
							            data: { confirm: 'Do you want to delete this invoice? Assoicated shipments will be marked as uninvoiced.' } %>
                                    <% else %>
                                    -
                                    <% end %>
								</td>
								<td>
								  <%= invoice.sent_to_economic ? "Yes" : "No" %>
                                  <% if invoice.editable? %>
									<%= link_to 'Submit', submit_invoice_path(invoice), method: :post,
									    data: invoice.sent_to_economic ? { confirm: 'This invoice has already been sent to economic once. Would you like to send this invoice to economic again?' } : {} %>
                                    <% end %>
								</td>
								<td>
								  <% if @user.can_pay_online %>
								  <%= invoice.captured_online ? "Yes" : "No" %>
								  <% else %>
								  -
								  <% end %>
									<% if invoice.capturable? %>
									<%= link_to 'Capture now', capture_invoice_path(invoice), method: :post %>
									<% end %>	
								</td>
                                <td>
                                  <%= invoice.paid?  ? "Yes" : "No" %>
                                </td>
							<!--	<td>
									<% if invoice.economic_id %>
										<%= invoice.economic_id%>
									<% elsif invoice.sent_to_economic %>
										<%= link_to 'Identify e-conomic id', identify_economic_id_path(invoice), method: :post %>	
									<% else %>
										Not sent to e-conomic.
									<% end %>
							</td> -->
							</tr>
						<% end %>
					</tbody>					
				</table>
				<%= grid_after @invoices%>
			</div>
		</div>
	</div>
</div>