config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post :add_product
      post :set_product_alias
      post :remove_product
      post :fetch_address_from_economic
      get :edit_products
      get :edit_contact_address
      get :affiliate_dashboard
      
      patch :update_contact_address
      resources :products, only: [] do
        get :edit_price_scheme
        patch :update_price_scheme
        patch :default_price_scheme
        patch :cargoflux_price_scheme
      end
      
      get :epay_subscribe
      get :shipments
    end
  end

  resources :products do
    member do
      get :edit_cost
      patch :update_cost_scheme
      get :edit_default_price
      patch :update_default_price_scheme
    end
  end

  resources :transporters

  resources :shipments do
    member do
      post :submit
      post :callback
      post :reprint
      post :email
      get :copy
    end
  end
  post 'shipments/calculate_price', to: 'shipments#calculate_price'
  post 'shipments/upload_csv', to: 'shipments#upload_csv'
  get 'bulk_import', to: 'shipments#bulk_import'

  resources :invoices, only: [:show] do
    get :shipments
    get :export_rows
  end
  resources :invoices, defaults: { format: 'xlsx' }
  
  resources :addresses do
    member do
      get :send_to
      get :json
    end
  end
  
  
  

  resources :import_formats do
    member do
      get :edit_for_user
    end
  end

  resources :invoices do
  end
  

  root 'sessions#index'
  post 'login', to: 'sessions#login_attempt'
  get 'home', to: 'sessions#home'
  get 'logout', to: 'sessions#logout'  
  get 'forgot_password', to: 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password'
  get 'urp/:email/:key', as: 'new_password', to: 'sessions#new_password', :constraints => { :email => /[^\/]+/ }
  post 'update_password', to: 'sessions#update_password'

  post 'api/products', to: 'api#product_codes'
  post 'api/create_shipment', to: 'api#create_shipment'
  post 'api/fresh_labels', to: 'api#fresh_labels'
  post 'api/recent_failures', to: 'api#recent_failures'
  post 'api/import', to: 'api#upload_csv'
  post 'api/validate_key', to: 'api#validate_key'
  post 'api/shipment_info', to: 'api#shipment_info'
  post 'api/client_version', to: 'api#client_version'
  post 'api/is_code_pickup_point', to: 'api#is_code_pickup_point'
  post 'api/pn/servicepoints', to: 'api#pn_servicepoints_by_address'
  post 'api/gls/servicepoints', to: 'api#gls_servicepoints_by_address'
  post 'api/dao/servicepoints', to: 'api#dao_servicepoints_by_address'
  post 'api/get_price', to: 'api#get_price'
  post 'api/economic_invoice_captured', to: 'api#economic_invoice_captured'
  post 'api/economic_invoice_updated', to: 'api#economic_invoice_updated'
  post 'api/update_pending_booking_states', to: 'api#update_pending_booking_states'
  post 'api/mark_shipment_printed', to: 'api#mark_shipment_printed'

  get 'account', to: 'account#index', as: 'account'
  get 'account/change_password', to: 'account#change_password', as: 'change_password'
  post 'account/do_change_password', to: 'account#do_change_password', as: 'do_change_password'
  get 'account/products', to: 'account#products', as: 'my_products'
  patch 'account/product/:id/', to: 'account#update_product', as: 'user_product'
  get 'account/invoices', to: 'account#invoices', as: 'my_invoices'
  get 'account/invoices/:id', to: 'account#invoices_show', as: 'my_invoices_show'
  get 'account/invoices/:id/download', to: 'account#invoice_download', as: 'download_invoice'
  get 'account/invoices/:id/shipments', to: 'account#invoices_shipments', as: 'my_invoices_shipments'
  get 'account/epay_subscribe', to: 'account#epay_subscribe', as: 'epay_subscribe'
  post 'account/epay_delete_subscription', to: 'account#epay_delete_subscription', as: 'epay_delete_subscription'

  get 'settings', to: 'settings#index', as: 'settings'
  patch 'settings/:id/update', to: 'settings#update', as: 'user_setting'

  get 'billing/user/:id', to: 'billing#user', as: 'user_billing'
  get 'billing/user/:id/edit_prices', to: 'billing#edit_prices', as: 'user_edit_prices'
  get 'billing/user/:id/edit_additional_charges', to: 'billing#edit_additional_charges', as: 'user_edit_additional_charges'
  post 'billing/invoice', to: 'billing#invoice', as: 'invoice_all'
  post 'billing/user/:id/update_prices', to: 'billing#update_prices', as: 'user_update_prices'
  post 'billing/user/:id/update_additional_charges', to: 'billing#update_additional_charges', as: 'user_update_additional_charges'
  post 'billing/user/:id/add_additional_charge', to: 'billing#add_additional_charge', as: 'user_add_additional_charge'
  post 'billing/invoice/:id/submit', to:'billing#submit_invoice', as: 'submit_invoice'
  post 'billing/invoice/:id/capture', to: 'billing#capture_invoice', as: 'capture_invoice' 
  post 'billing/invoice/:id/identify', to: 'billing#identify_economic_id', as: 'identify_economic_id'
  post 'billing/invoice/:id/send_email', to: 'billing#send_invoice_email', as: 'send_invoice_email'
  get 'billing', to: 'billing#overview', as: 'billing_overview'

  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  get 'admin/shipment/:id', to: 'admin#show_shipment', as: 'admin_shipment'
  get 'admin/tools', to: 'admin#tools', as: 'admin_tools'
  post 'admin/tools/verify_billable_shipments', to: 'admin#verify_billable_shipments', as: 'admin_verify_billable'
  post 'admin/tools/update_shipping_states', to: 'admin#update_shipping_states', as: 'admin_update_shipping_states'
  post 'admin/tools/update_booking_states', to: 'admin#update_booking_states', as: 'admin_update_booking_states'
  post 'admin/tools/automatic_invoicing', to: 'admin#automatic_invoicing', as: 'admin_automatic_invoicing'
  post 'admin/tools/fetch_economic_data', to: 'admin#fetch_economic_data', as: 'admin_economic_fetch'
  post 'admin/tools/process_additional_charges', to: 'admin#process_additional_charges', as: 'admin_process_additional_charges'
  post 'admin/tools/approve_additional_charges', to: 'admin#approve_additional_charges', as: 'admin_approve_additional_charges'
  post 'admin/tools/import_ftp_uploads', to: 'admin#import_ftp_uploads', as: 'admin_import_ftp_uploads'
  post 'admin/tools/apply_subscription_fees', to: 'admin#apply_subscription_fees', as: 'admin_apply_subscription_fees'
  post 'admin/tools/update_cargoflux_prices', to: 'admin#update_cargoflux_prices', as: 'admin_update_cargoflux_prices'
  
  get 'affiliate/dashboard', to: 'affiliate#dashboard', as: 'affiliate_dashboard'

end

app/models/pricing/intervals/interval_row.rb
class IntervalRow  < ActiveRecord::Base
  
  belongs_to :interval_table
  has_many :markup_rows, :foreign_key => 'cost_break_id', :dependent => :destroy
  
  validates :country_code, :presence => true
  validates :weight_from, :presence => true
  validates :weight_to, :presence => true
  validates :value, :presence => true
  validates :default_markup, :presence => true
  

  def s_country_code
    return country_code == nil ? '' : country_code
  end
  
  def sort_value
    ApplicationController.helpers.country_name(country_code) + weight_from.to_s.rjust(10, '0')
  end
  
end

app/models/pricing/intervals/interval_table.rb
class IntervalTable < PricingScheme
  
  
  has_many :rows, :class_name => :IntervalRow, :dependent => :destroy 
  
  has_many :markup_rows, :class_name => :MarkupRow, :dependent => :destroy
  
    
  
  def build
    #pass
  end
  
  def get_attrs params
    return params.require(:pricing_scheme).permit().merge(
        {:rows_attributes => params.require(:pricing_scheme).require(:rows_attributes)})
  end
  
  def handle_update params
    
    begin
      mrow_attrs = params.require(:pricing_scheme).require(:markup_rows_attributes)
      mrow_attrs.each do |id, vals|
        mrow = MarkupRow.find id
        mrow.markup = vals[:markup]
        mrow.active = vals[:active]
        mrow.save
      end
    rescue ActionController::ParameterMissing
    end
    
    begin
      row_attrs = params.require(:pricing_scheme).require(:rows_attributes)            
      row_attrs.each do |i,vals|        
        if vals[:id]
          row = IntervalRow.find vals[:id]
          if vals[:remove]
            row.destroy
          else
            row.value = vals[:value]
            row.default_markup = vals[:default_markup]
            row.save
          end          
        else
          row = IntervalRow.new
          row.country_code = vals[:country_code]
          row.weight_from = vals[:weight_from]
          row.weight_to = vals[:weight_to]
          row.value = vals[:value]
          row.default_markup = vals[:default_markup] ? vals[:default_markup] : 0
          row.interval_table = self          
          row.save
        end
      end
    rescue ActionController::ParameterMissing
    end
    
    save
  end
  
  def validate_overlapping_intervals attrs
    rows_attrs = attrs[:rows_attributes].values
    for i in 0 .. rows_attrs.length - 2 #Do not compare last element to itself
      i_attrs = rows_attrs[i]
      i_attrs[:weight_to] = i_attrs[:weight_to].to_f
      i_attrs[:weight_from] = i_attrs[:weight_from].to_f
      for j in i + 1 .. rows_attrs.length - 1
        j_attrs = rows_attrs[j]
        j_attrs[:weight_to] = j_attrs[:weight_to].to_f
        j_attrs[:weight_from] = j_attrs[:weight_from].to_f
        if i_attrs[:country_code] == j_attrs[:country_code] and i_attrs[:weight_to] > j_attrs[:weight_from] and j_attrs[:weight_to] > i_attrs[:weight_from]
          raise PriceConfigException.new 'UPDATE DROPPED: Overlapping intervals detected!'
        end
      end
    end
  end
  
  def validate_available_intervals attrs
    rows_attrs = attrs[:rows_attributes].values
    for row in rows_attrs
      accepted = false
      for cost_row in cost_scheme.rows
        if row[:country_code] == cost_row.country_code and row[:weight_from].to_f >= cost_row.weight_from and row[:weight_to].to_f <= cost_row.weight_to
          accepted = true
          break
        end
      end
      if not accepted
        raise PriceConfigException.new "UPDATED DROPPED: Interval not available: #{row[:country_code]} #{row[:weight_from]} -> #{row[:weight_to]}"
      end
    end
  end
  
  def handle_cost_update params
    set_diesel_fee_dk params.require(:pricing_scheme)[:diesel_fee_dk]
    set_diesel_fee_inter params.require(:pricing_scheme)[:diesel_fee_inter]
    handle_update params
  end
  
  
  def handle_price_update params
    dfe = params.require(:pricing_scheme).permit(:diesel_fee_dk, :diesel_fee_inter, :cargoflux_prices)
    set_extras_val(:diesel_fee_dk, dfe.key?(:diesel_fee_dk))
    set_extras_val(:diesel_fee_inter, dfe.key?(:diesel_fee_inter))
    set_extras_val(:cargoflux_prices, dfe.key?(:cargoflux_prices))
    begin
      validate_available_intervals(get_attrs(params))
    rescue ActionController::ParameterMissing
    end
    handle_update params
  end
  
 
  
  def available_countries
    countries = Set.new
    for row in markup_rows
      if row.active
          countries.add(row.cost_break.country_code)
      end
      
    end
    return countries.to_a
  end
  
  def product_rows country
    res = []
    markup_rows.each do |row|
      if row.cost_break.country_code == country
        res.push({:title => "#{country} #{row.cost_break.weight_from} kg - #{row.cost_break.weight_to} kg", 
        :price => row.markup + row.cost_break.value})
      end
    end    
    return res
  end
  
  def price_configured? shipment
    shipment.packages.each do |package|      
      if not  markup_rows.joins(:cost_break).where(['active = 1 AND country_code LIKE ? AND weight_from <= ? AND weight_to > ?',
          shipment.recipient.country_code, package.weight, package.weight]).exists?
        return false
      end     
    end
    return true
  end
  
  def get_cost shipment, cache = true    
    return get_price(shipment, cache)
  end
  
  
  def get_price shipment, cache = true
      val = 0      
      title = "#{shipment.product.name}: #{shipment.recipient.country_code}"
      
      if self.pricing_type == 'cost'
        cost_scheme = self
      else
        cost_scheme = get_cost_scheme
      end
      
      shipment.packages.each do |package|
        begin
          cost_row = get_cost_row cost_scheme, shipment, package
          if self.pricing_type == 'cost'
            package.cost = cost_row.value * package.amount
            if cache
              package.save
            end
            val += package.cost
          else     
            markup_row = get_markup_row cost_row
            package.price = (markup_row.markup + cost_row.value) * package.amount
            package_class = "(#{cost_row.weight_from} - #{cost_row.weight_to} kg)"
            package.title = "#{title} #{package_class}"
            if cache
              package.save
            end
            val += package.price
          end
        rescue ActiveRecord::RecordNotFound
          issue = "WARNING: No price configured for country #{shipment.recipient.country_code}, weight #{package.weight} (shipment id #{shipment.pretty_id} user #{shipment.user.email})"
          Rails.logger.warn issue
          raise PriceConfigException.new issue
        end
      end
      return val 
  end
  
  def get_cost_row cost_scheme, shipment, package
    country_code = shipment.product.is_import ? shipment.sender.country_code : shipment.recipient.country_code
    return cost_scheme.rows.where(['country_code LIKE ? AND weight_from <= ? AND weight_to > ?',
      country_code, package.weight, package.weight]).first!
  end
  
  def get_markup_row cost_row
    return MarkupRow.where(:cost_break => cost_row, :interval_table => self, :active => true).first!    
  end
  
  def get_markup_rows
    cost_scheme = get_cost_scheme      
    mrows = []
    cost_scheme.rows.order(:country_code, :weight_from).each do |crow|
      mrow = MarkupRow.where(:interval_table => self, :cost_break => crow).first
      if mrow == nil
        mrow = MarkupRow.new
        mrow.interval_table = self
        mrow.cost_break = crow
        mrow.save
      end
      mrows.append mrow
    end
    return mrows
  end
  
  
  def generate_invoice_rows shipments

    fee_dk = 0
    fee_inter = 0
    hash = {}
    shipments.each do |shipment|
      package_total = 0  
      if shipment.has_package_prices
        # NEW INVOICE METHOD WITH INDIVIDUAL PRICES FOR PACKAGES  
        # ALSO ADDS A "MANUAL DISCOUNT" LINE TO HANDLE UPDATED
        # FINAL PRICE VALUES
        shipment.packages.each do |package|
          title = package.title
           if hash.key? title
              hash[title][:price] += package.price
              hash[title][:count] += package.amount
              hash[title][:cost] += package.cost
            else
              hash[title] = {:price => package.price, :count => package.amount,
                             :cost => package.cost}
            end
        end
        if shipment.final_price < shipment.price
          # Register manual discount
          title = 'Manual Discount'
          if hash.key? title
            hash[title][:price] += shipment.final_price - shipment.price
            hash[title][:count] += 1
            hash[title][:cost] += package.cost
          else
            hash[title] = {:price => shipment.final_price - shipment.price, :count => 1,
                            :cost => 0}
          end
        end
      else
        # OLD INVOICE METHOD
        title = "#{shipment.product.name}: #{shipment.recipient.country_code}"
        
        classes = {}
        shipment.packages.each do |package|
          begin
            row = rows.where(['country_code LIKE ? AND weight_from <= ? AND weight_to > ?', shipment.recipient.country_code, package.weight, package.weight]).first!
            package_class = "#{row.weight_from} - #{row.weight_to} kg"
          rescue ActiveRecord::RecordNotFound
            if shipment.final_price.blank? or shipment.cost.blank?
              issue = "WARNING: No price configured for country #{shipment.recipient.country_code}, weight #{package.weight} (shipment id #{shipment.pretty_id} user #{shipment.user.email})"
              Rails.logger.warn issue
              raise PriceConfigException.new issue
            else
              package_class = "#{package.weight} kg"
            end
          end
          if classes.key? package_class
            classes[package_class] += package.amount
          else
            classes[package_class] = package.amount
          end        
        end
        
        classes.sort.map do |k, v|
          title += " (#{k})"
        end
        
        if hash.key? title
          hash[title][:price] += shipment.final_price
          hash[title][:count] += 1
          hash[title][:cost] += shipment.cost
        else
          hash[title] = {:price => shipment.final_price, :count => 1,
                         :cost => shipment.cost}
        end
      end
      
      # -------------------------------------------------------------
      # FROM THIS LINE BELOW FUNCTIONALITY IS IDENTICAL FOR OLD VS NEW
      # -------------------------------------------------------------  

app/models/pricing/intervals/markup_row.rb
class MarkupRow  < ActiveRecord::Base
  
  belongs_to :interval_table 
  belongs_to :cost_break, :class_name => 'IntervalRow' , :foreign_key => 'cost_break_id', :primary_key => 'id'
  
  
end

app/models/pricing/price_config_exception.rb
class PriceConfigException < RuntimeError
  def initialize(issue)
    @issue = issue
  end
  
  def issue
    @issue
  end
end

app/views/pricing/interval/_table.html.erb
<% countries = (defined? countries).nil? ? false : countries%>

<%
if countries == []
	%>
	NO COUNTRIES AVAILABLE
	<%
else
%>
<div class='panel panel-default'>
	<div class='panel-heading'>
		Price Configuration
	</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Country</th>
					<th>Weight from (&lt;= weight)</th>
					<th>Weight to (&gt; weight)</th>
					<th>Value</th>
					<th class="col-md-1">Remove</th>
				</tr>
			</thead>
			<tbody id='matrix'>
			<% i = 0 %>
			<% (@scheme.rows.all.sort {|a,b| a.sort_value <=> b.sort_value}).each do |row| %>
			<tr id='row-<%= i %>'>
				
				<td>
					<%= hidden_field("pricing_scheme[rows_attributes][#{i}]", 'id', :value => row.id)%>
					<%= bscountry_select("pricing_scheme[rows_attributes][#{i}]", "country_code", selected: row.s_country_code, only: countries)%>
				</td>
				<td>
					<%= bstxt_field("pricing_scheme[rows_attributes][#{i}]", 'weight_from', :value => row.weight_from)%>
				</td>
				<td>
					<%= bstxt_field("pricing_scheme[rows_attributes][#{i}]", 'weight_to', :value => row.weight_to)%>
				</td>
				<td>
					<%= bstxt_field("pricing_scheme[rows_attributes][#{i}]", 'value', :value => row.value)%>
				</td>
				<td>
					<%= bschckbx("pricing_scheme[rows_attributes][#{i}][remove]", '1') %>
				</td>
			</tr>
			<% i+=1 %>
			<% end %>
			</tbody>
			<tfoot>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td><button onclick='addRow()' type='button' class='btn btn-primary btn-block'>Add</button></td>	
			</tr>
			</tfoot>
		</table>	

	</div>
</div>


<table style='display:none'>
	<tr id='base-row'>
		<td>
			<%= bscountry_select("pricing_scheme[rows_attributes][{{x}}]", "country_code", only: countries)%>
		</td>
		<td>
			<%= bstxt_field("pricing_scheme[rows_attributes][{{x}}]", 'weight_from')%>
		</td>
		<td>
			<%= bstxt_field("pricing_scheme[rows_attributes][{{x}}]", 'weight_to')%>
		</td>
		<td>
			<%= bstxt_field("pricing_scheme[rows_attributes][{{x}}]", 'value')%>
		</td>
		<td>
			<button onclick='removeRow({{x}})' type='button' class='btn btn-danger btn-block'>X</button>
		</td>
	</tr>
</table>

<script type='text/javascript'>
	var nRows = <%= i %>;
	
	var baseRow = $('#base-row');
	var baseRowHtml = baseRow.html();
	baseRow.remove();
	function addRow(){
		nRows++;
		var html = baseRowHtml.replace(new RegExp('{{x}}', 'g'), nRows )
		var newRow = document.createElement('tr')
		newRow.id = 'row-' + nRows;
		newRow.innerHTML = html;
		$('#matrix').append(newRow);
	}
	
	function removeRow(i){
		var row = $('#row-' + i);
		row.remove();
	}
</script>

<% end %>

app/views/pricing/interval/price.html.erb
<h2 class='page-header'>Edit price scheme (<%= @user.name %>, <%= @product.name %>)
	<span class='pull-right'>
	  <%= link_to 'Set to Cargoflux', product_cargoflux_price_scheme_path(@user, @product), method: :patch,
				data: { confirm: 'Are you sure you want to set prices to Cargoflux values?' },
	      class: 'btn btn-default'%>
	  <%= link_to 'Reset to default', product_default_price_scheme_path(@user, @product), method: :patch,
				data: { confirm: 'Are you sure you want to reset prices to default values?' },
				class: 'btn btn-default'%>
	</span>
	</h2>
<%= form_for @scheme, :url => product_update_price_scheme_path(@user, @product) do |f| %>

<div class='panel panel-default'>
	<div class='panel-heading'>Diesel Fees</div>
	<div class='panel-body'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th><label for='pricing_scheme_dk_diesel_fee'>Enable diesel fee (DK)</label></th>
					<th><label for='pricing_scheme_dk_diesel_fee'>Enable diesel fee (International)</label></th>
					<th><label for='pricing_scheme_cargoflux'>Enable Cargoflux prices</label></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
					  <%= bschckbx('pricing_scheme[diesel_fee_dk]', 1, @scheme.diesel_fee_dk_enabled?) %>
					</td>
					<td>
					  <%= bschckbx('pricing_scheme[diesel_fee_inter]', 1, @scheme.diesel_fee_inter_enabled?) %>
					</td>
					<td>
					  <%= bschckbx('pricing_scheme[cargoflux_prices]', 1, @scheme.cargoflux_prices_enabled?) %>
					</td>
				</tr>
			</tbody>			
		</table>
	</div>
</div>

<% if false %>
<%= render :partial => 'pricing/interval/table', :locals => {:countries => @product.cost_scheme.available_countries} %>
<% end %>
<div class="panel panel-default">
	<div class="panel-heading">Markup configuration</div>
	<div class="panel-body">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Country</th>
					<th>Weight from</th>
					<th>Weight to</th>
					<th>Cost</th>
					<th>Default Markup</th>
					<th>Markup <span class="pull-right"><button onclick="copyDefaultMarkup();" type="button" class="btn btn-primary">Use defaults</button></span></th>
					<th>Total Price</th>
					<th><label for="markup-active-all">Active</label><input type="checkbox" id="markup-active-all" onclick="toggleMarkupActiveAll()"/></th>
				</tr>
			</thead>
			<tbody>
				<% markup_rows = @scheme.get_markup_rows %>

				<% i = 0;%>
				<% markup_rows.each do |row| %>
				<tr>
					<td>
						<%= row.cost_break.country_code %>
					</td>
					<td>
						<%= row.cost_break.weight_from %>
					</td>
					<td>
						<%= row.cost_break.weight_to %>
					</td>
					<td>
						<%= currency row.cost_break.value %>
						<%= hidden_field("pricing_scheme[rows_attributes][#{i}]", 'cost', :value => row.cost_break.value,
					:onchange => "updateDefaultPrice(this);", :class => 'input-cost', :disabled => true)%>
					</td>
					<td>
						<%= currency row.cost_break.default_markup %>
						<input type="hidden" id="default-markup-<%= i %>" value=<%= row.cost_break.default_markup %>>
					</td>
					<td>
						<%= bstxt_field("pricing_scheme[markup_rows_attributes][#{row.id}]", 'markup',
						:value => row.markup, :id => "markup-#{i}", :onchange => "updatePrice(this);", :class => 'input-markup')%>
					</td>
					<td>
						<%= bstxt_field("pricing_scheme_price[rows_attributes][#{i}]", 'edit_price', 
							:value => row.cost_break.value + row.markup, :onchange => "updateFinalPrice(this);", :class => 'input-price-showing')%>
							
							<%= hidden_field("pricing_scheme[rows_attributes][#{i}]", 'price', 
							:value => row.cost_break.value + row.markup, :disabled => true, :class => 'input-price')%>
					</td>
					<td>
						<%= bschckbx("pricing_scheme[markup_rows_attributes][#{row.id}][active]", '1', row.active, {:class => 'markup-active'})%>
					</td>
					
				</tr>
				<% i += 1; %>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	N_MARKUPS = <%= i %>;
	function copyDefaultMarkup(){
		for(i=0; i<N_MARKUPS; i++){
			$('#markup-' + i).val($('#default-markup-' + i).val());
			$('#markup-' + i).change();
		}
	}
	
	function isAllMarkupActive(){
		return $.grep($('.markup-active'), function(checkbox){
			return !checkbox.checked;
		}).length == 0;
	}
	
	function updateMarkupActiveAll(){		
		if(isAllMarkupActive()){
			$('#markup-active-all').prop('checked', true);
		}else{
			$('#markup-active-all').prop('checked', false);
		}
	}
	
	function toggleMarkupActiveAll(){
		if(isAllMarkupActive()){
			$('.markup-active').prop('checked', false);
		}else{
			$('.markup-active').prop('checked', true);
		}
	}
	
	
	$('.markup-active').change(function(){
		updateMarkupActiveAll()
	});
	
	$(document).ready(function(){
		updateMarkupActiveAll();
	});
	
	function updatePrice(caller){
		var row = $(caller).parents().eq(1);
		var costField = row.find('.input-cost');		
		var markupField = row.find('.input-markup');			
		row.find('.input-price').val(parseFloat(costField.val()) + parseFloat(markupField.val()));
		row.find('.input-price-showing').val(parseFloat(costField.val()) + parseFloat(markupField.val()));
	}
	
	function updateFinalPrice(caller){
		var row = $(caller).parents().eq(1);
		var costField = row.find('.input-cost');		
		var priceFieldEdit = row.find('.input-price-showing');	
		var priceField = row.find('.input-price-showing');			
		row.find('.input-markup').val(parseFloat(priceFieldEdit.val()) - parseFloat(costField.val()));
		row.find('.input-price').val(parseFloat(priceFieldEdit.val()));
	}
</script>



<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>

<% end%>