config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      post :add_product
      post :set_product_alias
      post :remove_product
      post :fetch_address_from_economic
      get :edit_products
      get :edit_contact_address
      get :affiliate_dashboard
      
      patch :update_contact_address
      resources :products, only: [] do
        get :edit_price_scheme
        patch :update_price_scheme
        patch :default_price_scheme
        patch :cargoflux_price_scheme
      end
      
      get :epay_subscribe
      get :shipments
    end
  end

  resources :products do
    member do
      get :edit_cost
      patch :update_cost_scheme
      get :edit_default_price
      patch :update_default_price_scheme
    end
  end

  resources :transporters

  resources :shipments do
    member do
      post :submit
      post :callback
      post :reprint
      post :email
      get :copy
    end
  end
  post 'shipments/calculate_price', to: 'shipments#calculate_price'
  post 'shipments/upload_csv', to: 'shipments#upload_csv'
  get 'bulk_import', to: 'shipments#bulk_import'

  resources :invoices, only: [:show] do
    get :shipments
    get :export_rows
  end
  resources :invoices, defaults: { format: 'xlsx' }
  
  resources :addresses do
    member do
      get :send_to
      get :json
    end
  end
  
  
  

  resources :import_formats do
    member do
      get :edit_for_user
    end
  end

  resources :invoices do
  end
  

  root 'sessions#index'
  post 'login', to: 'sessions#login_attempt'
  get 'home', to: 'sessions#home'
  get 'logout', to: 'sessions#logout'  
  get 'forgot_password', to: 'sessions#forgot_password'
  post 'reset_password', to: 'sessions#reset_password'
  get 'urp/:email/:key', as: 'new_password', to: 'sessions#new_password', :constraints => { :email => /[^\/]+/ }
  post 'update_password', to: 'sessions#update_password'

  post 'api/products', to: 'api#product_codes'
  post 'api/create_shipment', to: 'api#create_shipment'
  post 'api/fresh_labels', to: 'api#fresh_labels'
  post 'api/recent_failures', to: 'api#recent_failures'
  post 'api/import', to: 'api#upload_csv'
  post 'api/validate_key', to: 'api#validate_key'
  post 'api/shipment_info', to: 'api#shipment_info'
  post 'api/client_version', to: 'api#client_version'
  post 'api/is_code_pickup_point', to: 'api#is_code_pickup_point'
  post 'api/pn/servicepoints', to: 'api#pn_servicepoints_by_address'
  post 'api/gls/servicepoints', to: 'api#gls_servicepoints_by_address'
  post 'api/dao/servicepoints', to: 'api#dao_servicepoints_by_address'
  post 'api/get_price', to: 'api#get_price'
  post 'api/economic_invoice_captured', to: 'api#economic_invoice_captured'
  post 'api/economic_invoice_updated', to: 'api#economic_invoice_updated'
  post 'api/update_pending_booking_states', to: 'api#update_pending_booking_states'
  post 'api/mark_shipment_printed', to: 'api#mark_shipment_printed'

  get 'account', to: 'account#index', as: 'account'
  get 'account/change_password', to: 'account#change_password', as: 'change_password'
  post 'account/do_change_password', to: 'account#do_change_password', as: 'do_change_password'
  get 'account/products', to: 'account#products', as: 'my_products'
  patch 'account/product/:id/', to: 'account#update_product', as: 'user_product'
  get 'account/invoices', to: 'account#invoices', as: 'my_invoices'
  get 'account/invoices/:id', to: 'account#invoices_show', as: 'my_invoices_show'
  get 'account/invoices/:id/download', to: 'account#invoice_download', as: 'download_invoice'
  get 'account/invoices/:id/shipments', to: 'account#invoices_shipments', as: 'my_invoices_shipments'
  get 'account/epay_subscribe', to: 'account#epay_subscribe', as: 'epay_subscribe'
  post 'account/epay_delete_subscription', to: 'account#epay_delete_subscription', as: 'epay_delete_subscription'

  get 'settings', to: 'settings#index', as: 'settings'
  patch 'settings/:id/update', to: 'settings#update', as: 'user_setting'

  get 'billing/user/:id', to: 'billing#user', as: 'user_billing'
  get 'billing/user/:id/edit_prices', to: 'billing#edit_prices', as: 'user_edit_prices'
  get 'billing/user/:id/edit_additional_charges', to: 'billing#edit_additional_charges', as: 'user_edit_additional_charges'
  post 'billing/invoice', to: 'billing#invoice', as: 'invoice_all'
  post 'billing/user/:id/update_prices', to: 'billing#update_prices', as: 'user_update_prices'
  post 'billing/user/:id/update_additional_charges', to: 'billing#update_additional_charges', as: 'user_update_additional_charges'
  post 'billing/user/:id/add_additional_charge', to: 'billing#add_additional_charge', as: 'user_add_additional_charge'
  post 'billing/invoice/:id/submit', to:'billing#submit_invoice', as: 'submit_invoice'
  post 'billing/invoice/:id/capture', to: 'billing#capture_invoice', as: 'capture_invoice' 
  post 'billing/invoice/:id/identify', to: 'billing#identify_economic_id', as: 'identify_economic_id'
  post 'billing/invoice/:id/send_email', to: 'billing#send_invoice_email', as: 'send_invoice_email'
  get 'billing', to: 'billing#overview', as: 'billing_overview'

  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  get 'admin/shipment/:id', to: 'admin#show_shipment', as: 'admin_shipment'
  get 'admin/tools', to: 'admin#tools', as: 'admin_tools'
  post 'admin/tools/verify_billable_shipments', to: 'admin#verify_billable_shipments', as: 'admin_verify_billable'
  post 'admin/tools/update_shipping_states', to: 'admin#update_shipping_states', as: 'admin_update_shipping_states'
  post 'admin/tools/update_booking_states', to: 'admin#update_booking_states', as: 'admin_update_booking_states'
  post 'admin/tools/automatic_invoicing', to: 'admin#automatic_invoicing', as: 'admin_automatic_invoicing'
  post 'admin/tools/fetch_economic_data', to: 'admin#fetch_economic_data', as: 'admin_economic_fetch'
  post 'admin/tools/process_additional_charges', to: 'admin#process_additional_charges', as: 'admin_process_additional_charges'
  post 'admin/tools/approve_additional_charges', to: 'admin#approve_additional_charges', as: 'admin_approve_additional_charges'
  post 'admin/tools/import_ftp_uploads', to: 'admin#import_ftp_uploads', as: 'admin_import_ftp_uploads'
  post 'admin/tools/apply_subscription_fees', to: 'admin#apply_subscription_fees', as: 'admin_apply_subscription_fees'
  post 'admin/tools/update_cargoflux_prices', to: 'admin#update_cargoflux_prices', as: 'admin_update_cargoflux_prices'
  
  get 'affiliate/dashboard', to: 'affiliate#dashboard', as: 'affiliate_dashboard'

end

app/helpers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_filter :authenticate_user, :except => ['callback']
  skip_before_action :verify_authenticity_token, :only => ['callback']

  def index
    #@shipments = @current_user.shipments.order(id: :desc)
    @shipments = @current_user.shipments.order(id: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @shipment = Shipment.find(params[:id])
  end

  def new
    @shipment = Shipment.new
    @shipment.user = @current_user
  end

  def edit
    @shipment = Shipment.find(params[:id])
    if !@shipment.can_edit
      redirect_to '/'
    end
  end

  def create
    @shipment = Shipment.new(shipment_params)

    sender = Address.new(address_params(:sender))
    recipient = Address.new(address_params(:recipient))

    if !sender.valid? || !recipient.valid?
      render 'new'
      return
    end


    sender.save
    recipient.save

    @shipment.sender_address_id = sender.id
    @shipment.recipient_address_id = recipient.id
    @shipment.user_id = @current_user.id

    if @shipment.save
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end
  
  def bulk_import

  end

  def upload_csv
    uploaded_file = params[:file]
    file_content = uploaded_file.read
    res = Shipment.import_csv file_content, @current_user

    if res['error']
      flash[:error] = res['msg']
    end
    redirect_to :action => 'index'
  end

  def update
    shipment = Shipment.find(params[:id])
    shipment.update(shipment_params)
    shipment.sender.update(address_params(:sender))
    shipment.recipient.update(address_params(:recipient))


    redirect_to :action => 'show'
  end

  def submit
    shipment = Shipment.find(params[:id])
    if !shipment.can_submit || shipment.user != @current_user
      redirect_to '/'
      return
    end

  #  render :text => shipment.request_data.to_json
  #  return
    response = shipment.submit
    #render :text => "Response #{response}. Shipment status: #{shipment.status}"
    redirect_to :action => 'show'
  end


  def callback
    shipment = Shipment.find(params[:id])

    if params['status'] == 'booked'
      shipment.status = 'complete'
      shipment.awb = params['awb']
      shipment.document_url = params['awb_asset_url']
    else
      shipment.status = 'failed'
    end

    shipment.api_response = params.to_json
    shipment.label_pending = true

    shipment.save
    redirect_to '/'
  end

  def reprint
    shipment = Shipment.find(params[:id])

    if !shipment.status == :complete && !shipment.status == :failed
      flash[:error] = "Invalid shipment status"
    else
      shipment.label_pending = true
      shipment.save
    end
    redirect_to :action => 'show'
  end

  private

  def shipment_params
    params.require(:shipment).permit(:product_id, :return,
                                     :package_length, :package_width,
                                     :package_height, :package_weight)
  end

  def address_params(prefix)
    params.require(prefix).permit(:company_name, :attention, :address_line1,
                                  :address_line2,:zip_code,
                                  :city, :phone_number,
                                  :email, :country_code)
  end

end

app/helpers/shipments_helper.rb
# Shipment form helper
module ShipmentsHelper
  def form_address_new(type)
    return @current_user.default_address if type == 'sender' &&
                                            @current_user.default_address

    if type == 'recipient' && params[:send_to]
      address = Address.find params[:send_to]
      return address if @current_user.addresses_include? address
    end
    Address.new
  end

  def form_address_edit(shipment, type)
    return shipment.sender if type == 'sender'
    return shipment.recipient if type == 'recipient'
  end

  def form_address(shipment, type)
    if shipment.new_record? && !@cloning
      form_address_new(type)
    else
      form_address_edit(shipment, type)
    end
  end
end

app/views/shipments/_address_form.html.erb
<%= cbox_subheader(prefix) do-%>

<% end %>

<div class='address-input-container'>
	<div class='form-group'>
	<% quick_select_addresses = @current_user.quick_select_addresses prefix %>
  	<%= bssel('select-' + prefix, options_from_collection_for_select(quick_select_addresses, :json_url, :short_desc), {include_blank: 'Quick select ' + prefix + '..'}) %>
	  <script type='text/javascript'>

		$('#select-<%= prefix %>').change(function(event){
			var sel = event.currentTarget;
			if(sel.selectedIndex > 0){
				$.getJSON(sel.value, function(json){
					$.each(json, function(key, value){
						var el = $("#<%= prefix %>_" + key);
						if(el.length){
							el.val(value);
						}
					});
				});
			}
		});
	  </script>
	</div>
	<div class='form-group'>
		<label>Company / Recipient Name <span class='required'>*</span></label>
		<%= bstxt_field(prefix, :company_name, :value => address.company_name, :required => true) %>
	</div>
 	<div class='form-group'>
		<label>Attention <span style='display:none' class='required' id='label-attention-<%= prefix %>'>*
				<span class='tip' data-toggle='tooltip'
					title='When using products that send to parcelshops the Attention field should contain the name of the actual recipient while the Company field should contain the name of the parcelshop.'></span></label>
		<%= bstxt_field(prefix, :attention, :value => address.attention) %>
	</div>
	<div class='form-group'>
		<label>Address Line 1 <span class='required'>*</span></label>
		<%= bstxt_field(prefix, :address_line1, :value => address.address_line1, :required => true) %>
	</div>
	<div class='form-group'>
		<label>Address Line 2</label>
		<%= bstxt_field(prefix, :address_line2, :value => address.address_line2) %>
	</div>
	<div class='form-group'>
		<label>Country <span class='required'>*</span></label>
		<%= bscountry_select(prefix, 'country_code', {selected: address.country_code, required: true}, { class: 'country-input'})%>
	</div>
	<div class='form-group'>
		<label>Zip Code <span class='required'>*</span></label>
		<%= bstxt_field(prefix, :zip_code, {value: address.zip_code, required: true, class: 'zip-input'}) %>
	</div>
	<div class='form-group'>
		<label>City <span class='required'>*</span></label>
		<%= bstxt_field(prefix, :city, value: address.city, required: true, class: 'city-input') %>
	</div>		
	<div class='form-group'>
		<label>Phone</label>
		<%= bstxt_field(prefix, :phone_number, :value => address.phone_number) %>
	</div>
	<div class='form-group'>
		<label>Email <span class='required'>*</span></label>
		<%= bstxt_field(prefix, :email, :value => address.email, :required => false) %>
	</div>
</div>

	

app/views/shipments/_address_show.html.erb
<div class='address-show'>
    <%= address.company_name %><br/>
    <%= address.attention %><br/>
    <%= address.address_line1 %><br/>
    <% if address.address_line2 != '' %>
    <%= address.address_line2 %><br/>
    <% end %>
    <%= address.country_code %><br/>
    <%= address.zip_code %><br/>
    <%= address.city %><br/>    
    <%= address.phone_number %><br/>
    <%= address.email %>
</div>

app/views/shipments/_calculated_price.html.erb
<% if shipment.has_package_prices %>
<table class='table shipment-price-calc col-md-12'>
	<thead>
		<tr>
			<th>Weight</th><th>Unit price</th><th>Amount</th><th>Price</th>
		</tr>
	</thead>
	<tbody>
		<% shipment.packages.each do |p| %>
		<tr>
			<td><%= p.weight %> kg</td>
			<td><%= currency (p.price / p.amount)%> </td>
			<td><%= p.amount %></td>
			<td><%= currency p.price %></td>
		</tr>
		<% end %>
		<tr>
			<td><b>Total</b></td>
			<td></td>
			<td></td>
			<td><b><%= currency shipment.price %></b></td>
		</tr>
	</tbody>
</table>	
<% else %>
<%= currency shipment.price %>
<% end %>

app/views/shipments/bulk_import.html.erb
<%= cbox do-%>

 <%= cbox_header ('Bulk import') do-%>
 
 <%end%>
<p>Bulk import allows you to generate multiple shipments using data contained in a single file.</p>


<% if @current_user.import_format and @current_user.import_format.complete? %>


	<p>Please make sure that your file comforms to the predefined import format.</p>
	
  <%= form_tag '/shipments/upload_csv', :multipart=>true do %>



  	<label for="file">
   		<button type="button" onclick="$('#file').click()" class="btn btn-default" >Select file <span id="file-dest"></span></button>
	</label>
	<input id="file" type="file" name="file" style="visibility: hidden; display: inline; width: 0;">
  	<button type="submit" class="btn btn-primary">Submit</button>

  <script type="text/javascript">
  	$(document).on('change', ':file', function() {
    	var input = $(this),        
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');        
        label = label == '' ? '' : '(' + label + ')'
    	$('#file-dest').html(label);
		});
  </script>
 	
  <% end %>
  <%else %>
<div class='error'>
	This functionality requires you to define an import format. Please contact the eShip administration.
</div>
<% end %>

<% end %>

app/views/shipments/edit.html.erb
<%= render :partial => 'form', :locals => {:title => "Edit shipment ##{@shipment.pretty_id}"} %>

app/views/shipments/index.html.erb
<%= cbox do-%>

 <%= cbox_header ('Shipments') do-%>  
 	<%= btn_link(url_for(bulk_import_path), 'Bulk Import')%>
 	<%= btn_link(url_for(new_shipment_path), 'New Shipment', 'primary')%>	
 <% end %>

<%= form_tag({:action => 'index'}, {:method => :get}) do %>
<%= cbox_grid_paging @shipments, true %> 
  <%= tbl true do-%>	 
	<thead>
		<tr>
	      <th>Shipment</th>
	      <th>AWB</th>
	      <th>Reference</th>
	      <th>Recipient</th>
	      <th>Timestamp</th>
	      <th>Product</th>
	      <th>Booking</th>
	      <th>Shipping	</th>	  	 
	    </tr>
	    <tr class='model-filters'>
	    	<td><input class='form-control' type='text' name='id' value='<%= params[:id] %>'/></td>
	    	<td><input class='form-control' type='text' name='awb' value='<%= params[:awb] %>'></td>
	    	<td><input class='form-control' type='text' name='reference' value='<%= params[:reference] %>' /></td>
	    	<td><input class='form-control' type='text' name='recipient' value='<%= params['recipient'] %>' /></td>
	    	<td class='date-filter'>
	    		<%= date_filter %>
	    	</td>
	    	<td></td>
	    	<td>
	    		<%= bssel :booking_state, options_for_select(Shipment.booking_state_options(false), params[:booking_state]) %>
	    	</td>
	    	<td>
	    		<%= bssel :shipping_state, options_for_select(Shipment.shipping_state_options(false), params[:shipping_state]) %>
	    	</td>	    	
	    </tr>
	</thead>
  	<tbody>
  		<% maxw = 100 %>
		<% @shipments.each do |shipment| %>
			<%= row_link(shipment_path(shipment)) do-%>
		      <td><%= link_to "#{shipment.pretty_id}", shipment_path(shipment) %></td>
		      <%= cell_safe shipment.awb, maxw %>
		  	  <%= cell_safe shipment.reference, maxw %>
		  	  <%= cell_safe shipment.recipient.company_name, maxw %>
		  	  <%= cell_safe print_datetime(shipment.created_at), 150 %>
		      <%= cell_safe shipment.product.name, maxw %>		      
		      <td><%= shipment.status.to_s.capitalize %></td>
		      <td><%= shipment.shipping_state.to_s.capitalize %></td>		      
	    	<% end %>
	    <% end %>
	</tbody>	
  <% end %>
  <%= cbox_grid_paging @shipments %>
<% end %>
<% end %>

app/views/shipments/new.html.erb
<%= render :partial => 'form', :locals => {:title => 'New shipment'} %>

app/views/shipments/show.html.erb
<div class='shipment-show'>
<%= cbox do-%>
<%= cbox_header("Shipment ##{@shipment.pretty_id}") do-%>
	<% if @shipment.can_edit %>
		<a href='<%= url_for edit_shipment_path(@shipment) %>' class='btn btn-primary' role='button'>Edit</a>
	  	<% else %>
		<% if not @disable_actions %>
	  	<a href='<%= url_for copy_shipment_path(@shipment) %>' class='btn btn-primary' role='button'>Copy</a>
	  	<% end %>
	<% end %>
<%end%>
<% if @shipment.status == 'failed' %>
  <div class='alert alert-danger'>
    <strong>Error:</strong> <%= @shipment.api_response_error_msg %>
  </div>
  <% end %>
  
  <div class='row'>
  	<div class='col-xs-4'>
  		<%
  		 data = {
  		 	'id' => "##{@shipment.pretty_id}",
  		 	'timestamp' => print_datetime(@shipment.created_at),
  		 	'booking state' => @shipment.status,
  		 	'shipping state' => @shipment.shipping_state,
  		 	'invoice' => @shipment.invoiced ? link_to("#{@shipment.invoice.pretty_id}", my_invoices_show_path(@shipment.invoice)) : "-"  		 	
  		 }
  		%>
  		<%= kv_box data %>
	</div>
  	<div class='col-xs-4'>  		  	
        <%
  		 label_action = @shipment.label_action_title.to_s
  		 if @shipment.can_print  		 	
  		 	label_action += ' -'
	        if @shipment.label_action == 'print'
	        	if @shipment.recent_label_pending?
	        		label_action += 'pending..'
	        	else	        		
	        		label_action += link_to(' Print again', reprint_shipment_path(@shipment), method: :post) 
	        	end
	        elsif @shipment.label_action == 'email'
	        	label_action += link_to 'Send again', email_shipment_path(@shipment), method: :post
	        end
  		 end
  		 data = {  		 	
			'AWB' =>  @shipment.can_print ? link_to(@shipment.awb, @shipment.tracking_url, :target => '_blank') : '-',
			'Document' => @shipment.can_print ? link_to("Download label", @shipment.document_url, :target => '_blank') : '-',
			'Label Action' => label_action,
			'Product' => @shipment.product.name,
			'Return service' => @shipment.return ? 'Yes' : 'No'
  		 }
  		%>
  		<%= kv_box data %>
  	</div>
  	
  	<div class='col-xs-4'>
  		<%
  		data = {
  			'Parcelshop id' => @shipment.parcelshop_id,
  			'Del. Instr.' => @shipment.delivery_instructions,
  			'Remarks' => @shipment.remarks,
  			'Content Descr.' => @shipment.description,
  			'Reference' => @shipment.reference
  		}
  		%>
  		<%= kv_box data%>
  	</div>	
  </div>
<%end%>
	 
<% if @shipment.status == 'response_pending'%>
	<script type='text/javascript'>var autoReload = true;</script>
<% end %>


<% if @shipment.dutiable %>
<%= cbox do-%>
<%= cbox_header('Customs') do-%>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <th>Amount</th><th>Currency</th><th>Code</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @shipment.customs_amount %></td>
      <td><%= @shipment.customs_currency %></td>
      <td><%= @shipment.customs_code %></td>
    </tr>
  </tbody>
</table>

<% end %>
<% end %>



 <%= cbox do-%>
 <%= cbox_header('Packages') do-%>
 
 <%end%>
 
 <table class='table'>
	<thead>
		<tr>
  			<th>Length</th>
  			<th>Width</th>
  			<th>Height</th>
  			<th>Weight</th>
  			<th>Amount</th>
  		</tr>
	</thead>
	<tbody>
		<% @shipment.packages.each do |package| %>
  		<tr>
  			<td><%= package.length %></td>
  			<td><%= package.width %></td>
  			<td><%= package.height %></td>
  			<td><%= package.weight %></td>
  			<td><%= package.amount %></td>
  		</tr>
  		<% end %>
	</tbody>
</table>
 <%end%>
 
<%= cbox do-%>
 <%= cbox_header('Addresses') do-%>

 <%end%>

<div class='row'>
 	<div class='col-xs-6'>
 		<%=cbox_subheader('sender') do-%>
 		
 		<%end%>
 		<%= render :partial => 'shipments/address_show', :locals => {:address => @shipment.sender }%>
	</div>
 	<div class='col-xs-6'>
		<%= cbox_subheader('recipient') do-%>
		
		<%end%>
		<%= render :partial => 'shipments/address_show', :locals => {:address => @shipment.recipient}%>
 	</div>	
</div> 
<%end%>  

<% if @shipment.value_determined %>
<%= cbox do-%>
<%= cbox_header('Prices') do-%>

<% end%>

<div class='row'>
	<div class='col-xs-6'>
		<%= block_kv_pair('Calculated shipment price') do-%>
		<%= render :partial => 'shipments/calculated_price', :locals => {:shipment => @shipment } %>
		<%end %>
	</div>
	<div class='col-xs-6'>
		<%= kv_box({
			'Adjusted shipment price' => currency(@shipment.final_price),
			'Calculated diesel fee' => currency(@shipment.diesel_fee),
			'Adjusted diesel fee' => currency(@shipment.final_diesel_fee)
		}, false)%>
	</div>
</div>

<% if @shipment.additional_charges.length > 0 %>

<table class='table'>
	<thead>
		<tr>
			<th>Additional Service Charge</th>
			<% if current_user.admin? %><th>Cost</th><% end %>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<% @shipment.additional_charges.each do |c| %>
			<tr>
				<td><%= c.description %></td>
				<% if current_user.admin? %><td><%= currency c.cost %></td><% end %>
				<td><%= currency c.price %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<% end %>
<%end%>
<%end%>
  
 
</div>

<script type='text/javascript'>
	if(autoReload === true){
		var initialPage = window.location.href;
		setInterval(
	    	function(){
	    		if(window.location.href != initialPage){
	    			return false;
	    		}
      			location.reload();
		     },60000 );
	}
</script>